server:
  port: 8189
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:otus1.p12
    key-store-password: 123456
    key-alias: otus
  servlet:
    context-path: /app
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:appdb;MODE=PostgreSQL
    username: sa
    password:
  h2:
    console:
      enabled: true
logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: TRACE